-- Relabel an existing custom calendar table without regenerating it.
--
-- Use when a calendar was generated by the ThoughtSpot API (whose `monthly`
-- column carries the FISCAL year, so a January period inside a December-start
-- fiscal year reads "January 2024" for dates in January 2025).
--
-- What this rewrites, and what it deliberately does not:
--   "year"      -> YEAR("date")                      (Gregorian)
--   "monthly"   -> CONCAT("month", ' ', YEAR("date")) (Gregorian)
--   "quarterly" -> carried through UNCHANGED, so it keeps the source's
--                  FISCAL year. Rewriting it would silently renumber
--                  quarters that straddle a fiscal boundary. The output
--                  therefore has "monthly" and "quarterly" on different
--                  year bases, by design.
-- Any year prefix (FY2024) is dropped from "year" and "monthly", which are
-- rebuilt numerically, but survives on "quarterly".
-- This names all 30 contract columns explicitly, so it assumes a 30-column
-- source: a 10-column table, or one carrying an RLS discriminator as column
-- 31, will fail or lose that column. Regenerate instead in those cases.
--
-- Run with (--sf-profile takes <profile> directly, in angle brackets, not
-- curly braces — curly braces below are --var-filled placeholders, and
-- ts snowflake exec scans the whole file for them, comments included):
--   ts snowflake exec -f references/relabel-calendar.sql --sf-profile <profile> \
--     --var source_db=CUSTOM_CALENDAR --var source_schema=PUBLIC \
--     --var source_table=julyoffset --var target_table=julyoffset_gregorian
CREATE OR REPLACE TABLE "{source_db}"."{source_schema}"."{target_table}" AS (
  SELECT
    "date",
    "day_of_week",
    "month",
    "quarter",
    YEAR("date")::VARCHAR                                   AS "year",
    "day_number_of_week",
    "week_number_of_month",
    "week_number_of_quarter",
    "week_number_of_year",
    "is_weekend",
    CONCAT("month", ' ', TO_VARCHAR(YEAR("date")))          AS "monthly",
    "quarterly",
    "day_number_of_month",
    "day_number_of_quarter",
    "day_number_of_year",
    "month_number_of_quarter",
    "month_number_of_year",
    "quarter_number_of_year",
    "absolute_week_number",
    "start_of_week_epoch",
    "end_of_week_epoch",
    "absolute_month_number",
    "start_of_month_epoch",
    "end_of_month_epoch",
    "absolute_quarter_number",
    "start_of_quarter_epoch",
    "end_of_quarter_epoch",
    "absolute_year_number",
    "start_of_year_epoch",
    "end_of_year_epoch"
  FROM "{source_db}"."{source_schema}"."{source_table}"
);
