#!/usr/bin/env node
// liveboard-pack.mjs [--liveboard <dir>] [--commit | --validate | --check]   (--commit requires --liveboard) (<slug> ... | --all) [--max 60000] [--list]
//
// Turns library charts into ready-to-paste MCP code that writes them straight into the target Liveboard.
// The Liveboard is its own store: nothing else is created in ThoughtSpot.
//
// Why blocks: the MCP sandbox keeps nothing between calls and a whole Liveboard is megabytes of chart code,
// so each block carries only some charts (up to --max characters) plus the spec and the shared core. The
// sandbox (scripts/patch.js) exports the Liveboard, replaces those charts' tiles, keeps every other tile as it
// is, imports, and proves the result. Paste the blocks in order; each one leaves a complete, working Liveboard.
//
//   --validate  (default) VALIDATE_ONLY import; changes nothing
//   --commit    ALL_OR_NONE import, then a round-trip proof
//   --check     one read-only block that compares every tile on the Liveboard with the library (no charts sent)
//   --all       every slug in <liveboard dir>/liveboard.spec.json
//   --list      print what would be sent, with sizes, and stop
//   --core-ref  send the shared core as a checksum only: the sandbox takes it from a tile already on the Liveboard.
//               Blocks after the first in one --commit run do this by themselves, since the first block puts the
//               core there (a --validate run writes nothing, so every block carries the core).
//   --reuse <liveboard guid>  send only checksums for these charts: the sandbox copies each one from that Liveboard
//               (found by its slug marker) when its body matches the library, and lists the rest under needCode.
//               Use it for library charts already on another Liveboard in the same cluster; it saves the paste.
// Charts come from the ts-object-answer-chart-builder skill's library/ (the full chart.{html,css,js}, so narrative
// tiles are sent as generated by build-narratives.mjs). Paste each block, unchanged, as the `code` of
// execute-thoughtspot-code with confirm_write_operations: true (--check needs no confirmation).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { chartSkill, skillDir } from "./chart-skill.mjs";

const lib = path.join(chartSkill(), "library");
const argv = process.argv.slice(2);
const VALUED = new Set(["--max", "--liveboard", "--reuse"]);
const flags = new Set(argv.filter((a, i) => a.startsWith("--") && !VALUED.has(argv[i - 1])));
const val = (k, d) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; };
const MAX = Number(val("--max", 60000));
// A commit writes to a real Liveboard, so it never falls back to the worked example: name the folder.
if (flags.has("--commit") && !argv.includes("--liveboard")) { console.error("--commit needs --liveboard <dir>: the folder whose liveboard.spec.json names the Liveboard to write"); process.exit(2); }
const LB = path.resolve(val("--liveboard", path.join(skillDir, "liveboards", "amuzing-chart-samples")));
const REUSE = val("--reuse", null);
const MODE = flags.has("--check") ? "check" : flags.has("--commit") ? "commit" : "validate";

const spec = JSON.parse(fs.readFileSync(path.join(LB, "liveboard.spec.json"), "utf8"));
if (!spec.liveboard) { console.error("liveboard.spec.json needs a top-level \"liveboard\" key (re-run make-spec.py)"); process.exit(2); }
const GUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const unset = [["liveboard", spec.liveboard.guid], ["model", spec.liveboard.model && spec.liveboard.model.guid]].filter(([, g]) => !GUID.test(g || ""));
if (unset.length && !flags.has("--list") && !process.env.LIVEBOARD_PACK_OFFLINE) { console.error("the spec has no real " + unset.map(([k]) => k).join(" or ") + " guid; set it in make-spec.py (the worked example reads LIVEBOARD_GUID and MODEL_GUID) and re-run it"); process.exit(2); }
const specSlugs = spec.tabs.flatMap((t) => t.tiles.map((x) => x.slug));
let slugs = argv.filter((a, i) => !a.startsWith("--") && !VALUED.has(argv[i - 1]));
if (flags.has("--all") || MODE === "check") slugs = [...new Set([...slugs, ...specSlugs])];
const notInSpec = slugs.filter((s) => !specSlugs.includes(s));
if (notInSpec.length) { console.error("not in the spec (add them to make-spec.py first): " + notInSpec.join(", ")); process.exit(2); }
if (!slugs.length) { console.error("usage: liveboard-pack.mjs [--commit|--validate|--check] (<slug> ... | --all)"); process.exit(2); }

const sha = (s) => crypto.createHash("sha256").update(s, "utf8").digest("hex");
const END = { js: "/* ==== end amuzing core ==== */", css: "/* ==== end amuzing core css ==== */" };
const OPEN = { js: /^\/\* ==== amuzing core v\d+[^\n]*\*\//, css: /^\/\* ==== amuzing core css v\d+[^\n]*\*\// };
// Shrink what ships: drop // comment lines, CSS comments except the core markers, and indentation. Safe because
// chart files are ASCII with no template strings (checked below). A 50-tile Liveboard goes from ~2.8 MB to ~1.8 MB.
const liteJs = (x) => x.split("\n").map((l) => l.replace(/^\s+/, "")).filter((l) => l && !/^\/\//.test(l)).join("\n");
const liteCss = (x) => x.replace(/\/\*(?! ====)[\s\S]*?\*\//g, "").split("\n").map((l) => l.replace(/^\s+/, "")).filter((l) => l).join("\n");
// How tiles imported before this scheme were trimmed (every CSS comment removed); only used by --check.
const liteCssLegacy = (x) => x.replace(/\/\*[\s\S]*?\*\//g, "").split("\n").map((l) => l.replace(/^\s+/, "")).filter((l) => l).join("\n");
const MARK_RE = /\/\* amuzing-slug: ([\w-]+) \*\//;

function split(txt, kind, what) {
  if (!OPEN[kind].test(txt)) throw new Error(`${what}: must start with the amuzing core marker (run the chart skill's helpers/sync-core.mjs)`);
  const i = txt.indexOf(END[kind]);
  if (i < 0) throw new Error(`${what}: unterminated core block`);
  return txt.slice(i + END[kind].length);
}
function lint(s, what) {
  if (s.includes("`")) throw new Error(`${what}: contains a backtick (the code is trimmed line by line; use quotes and +)`);
  if (s.includes("${")) throw new Error(`${what}: contains "\${"`);
  if (/[^\x09\x0a\x0d\x20-\x7e]/.test(s)) throw new Error(`${what}: contains non-ASCII characters`);
  if (/<\/script/i.test(s.replace(/<script\s+[^>]*\bsrc=["'][^"']+["'][^>]*><\/script>/gi, ""))) throw new Error(`${what}: contains </script`);
}

const coreJsFile = fs.readFileSync(path.join(lib, "_shared", "core.js"), "utf8").replace(/\s+$/, "");
const coreCssFile = fs.readFileSync(path.join(lib, "_shared", "core.css"), "utf8").replace(/\s+$/, "");
lint(coreJsFile, "core.js"); lint(coreCssFile, "core.css");
const core = { js: liteJs(coreJsFile), css: liteCss(coreCssFile) };
core.sha = { js: sha(core.js), css: sha(core.css) };

const tiles = {}, bodySha = {};
for (const slug of slugs) {
  const d = path.join(lib, slug);
  const read = (f) => fs.readFileSync(path.join(d, f), "utf8");
  const html = read("chart.html"), cssFull = read("chart.css"), jsFull = read("chart.js");
  if (!jsFull.includes(coreJsFile)) console.error("warning: " + slug + "/chart.js has an out-of-date core copy; the Liveboard gets the current core, run sync-core so the preview matches");
  const bodyJs = split(jsFull, "js", slug + "/chart.js"), bodyCss = split(cssFull, "css", slug + "/chart.css");
  lint(html, slug + "/chart.html"); lint(bodyJs, slug + "/chart.js"); lint(bodyCss, slug + "/chart.css");
  const f = { js: liteJs("/* amuzing-slug: " + slug + " */\n" + bodyJs), css: liteCss(bodyCss), html };
  tiles[slug] = { f, sha: { js: sha(f.js), css: sha(f.css), html: sha(f.html) } };
  bodySha[slug] = { js: sha(f.js.replace(MARK_RE, "").trim()), css: sha(f.css.trim()), html: sha(html), cssLegacy: sha(liteCssLegacy(coreCssFile + bodyCss)) };
  if (REUSE) tiles[slug] = { ref: { js: bodySha[slug].js, css: bodySha[slug].css, cssLegacy: bodySha[slug].cssLegacy, html: bodySha[slug].html, title: (spec.tabs.flatMap((t) => t.tiles).find((x) => x.slug === slug) || {}).title } };
}

if (flags.has("--list")) {
  for (const s of slugs) { const f = tiles[s].f; console.log(s.padEnd(30), f ? "js=" + f.js.length + " css=" + f.css.length + " html=" + f.html.length : "by reference from " + REUSE); }
  console.log("core js=" + core.js.length + " css=" + core.css.length + "  mode=" + MODE);
  process.exit(0);
}

const tpl = fs.readFileSync(path.join(skillDir, "scripts", "patch.js"), "utf8");
// Chart code goes in as String.raw literals with real line breaks (lint above guarantees no backtick or ${), so
// a block reads line by line when it is pasted; everything else is JSON. The sandbox re-checks every sha256.
const raw = (x) => "String.raw`" + x + "`";
const src = (payload) => {
  const out = ["{", "spec: " + JSON.stringify(payload.spec) + ",", "specSha: " + JSON.stringify(sha(JSON.stringify(payload.spec))) + ","];
  out.push("core: " + (payload.core && payload.core.ref ? "{ ref: true, sha: " + JSON.stringify(payload.core.sha) + " }" : payload.core ? "{ js: " + raw(payload.core.js) + ",\ncss: " + raw(payload.core.css) + ",\nsha: " + JSON.stringify(payload.core.sha) + " }" : "null") + ",");
  out.push("tiles: {");
  for (const [slug, t] of Object.entries(payload.tiles)) if (t.ref) out.push(JSON.stringify(slug) + ": { ref: " + JSON.stringify(t.ref) + " },"); else out.push(JSON.stringify(slug) + ": { f: { html: " + raw(t.f.html) + ",\ncss: " + raw(t.f.css) + ",\njs: " + raw(t.f.js) + " },\nsha: " + JSON.stringify(t.sha) + " },");
  out.push("},", "reuse: " + JSON.stringify(REUSE) + ",", "pending: " + JSON.stringify(payload.pending || []) + ",", "bodySha: " + JSON.stringify(payload.bodySha), "}");
  return out.join("\n");
};
const block = (payload) => tpl.replace("'__MODE__'", () => JSON.stringify(MODE)).replace("__PAYLOAD__", () => src(payload));
if (MODE === "check") {
  const h = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, v.slice(0, 16)]));
  const slim = { liveboard: spec.liveboard, tabs: spec.tabs.map((t) => ({ name: t.name, tiles: t.tiles.map((x) => ({ slug: x.slug, x: x.x, y: x.y })) })) };
  console.log(block({ spec: slim, core: null, tiles: {}, bodySha: Object.fromEntries(Object.entries(bodySha).map(([k, v]) => [k, h(v)])) }));
  console.error(`\n[liveboard-pack] read-only check of ${slugs.length} tile(s) on ${spec.liveboard.name}`);
  process.exit(0);
}
const blocks = [];
let cur = {}, size = 0;
const baseSize = JSON.stringify({ spec, core }).length + tpl.length;
for (const s of slugs) {
  const n = JSON.stringify(tiles[s]).length;
  if (size && baseSize + size + n > MAX) { blocks.push(cur); cur = {}; size = 0; }
  cur[s] = tiles[s]; size += n;
}
if (size) blocks.push(cur);
// Tiles still to come in later blocks are reported as pending, not as problems.
const coreRef = { ref: true, sha: core.sha };
console.log(blocks.map((t, i) => block({ spec, core: flags.has("--core-ref") || (i > 0 && MODE === "commit") ? coreRef : core, tiles: t, bodySha: {}, pending: blocks.slice(i + 1).flatMap((b) => Object.keys(b)) })).join("\n=====\n"));
console.error(`\n[liveboard-pack] ${slugs.length} tile(s) in ${blocks.length} block(s), mode ${MODE}: ` + blocks.map((b) => Object.keys(b).join(" ")).join(" | "));
