#!/usr/bin/env python3
"""Build the vendored `databricks_mv_lib` Genie notebook from ts-cli's pure modules.

Concatenates the Genie-vendorable closure (stdlib + PyYAML only — no HTTP, no
typer, no ts_cli.client) into one Databricks SOURCE notebook, stripping every
`from ts_cli.*` import so all names resolve in the single exec namespace.
Called by deploy.sh at deploy time; the output is generated, never committed.

Usage: python3 build_mv_lib.py --ts-cli-root ../../tools/ts-cli --out notebooks/databricks_mv_lib.py
"""
from __future__ import annotations

import argparse
import ast
import pathlib
import re
import sys

# Dependency order matters only for module-level statements; all cross-module
# calls resolve at call time in the shared namespace.
CLOSURE = [
    "ts_cli/tml_lint.py",
    "ts_cli/tml_common.py",
    "ts_cli/formula_common.py",
    "ts_cli/databricks/mv_expr.py",
    "ts_cli/databricks/mv_window.py",
    "ts_cli/databricks/mv_sql_constructs.py",
    "ts_cli/databricks/mv_sql.py",
    "ts_cli/databricks/mv_translate.py",
    "ts_cli/databricks/mv_window_translate.py",
    "ts_cli/databricks/mv_parse.py",
    "ts_cli/databricks/mv_tml.py",
    "ts_cli/databricks/mv_build_model.py",
]

_STRIP_PREFIXES = ("from ts_cli.", "from ts_cli ", "import ts_cli.", "import ts_cli ",
                   "from __future__")


def strip_internal_imports(source: str) -> str:
    """Drop `from ts_cli.*` / `from __future__` statements at ANY indent level,
    including parenthesized multi-line forms (state machine on paren depth).

    Assumptions (safe today, would mis-strip in these edge cases):
    - The paren-depth counter is not comment/string-aware — an import line
      whose trailing `#` comment contains an unbalanced paren would throw
      off the depth count and over/under-strip subsequent lines.
    - Backslash-continued `import` statements (`import ts_cli.foo \\`) are
      not recognized as continuations — only the parenthesized multi-line
      form is.
    Neither form appears anywhere in the CLOSURE modules today, and either
    would fail loud rather than silent: a mis-stripped closure either fails
    the `compile()` syntax gate in `build_source`, or fails
    `test_source_is_self_contained` / `test_end_to_end_parse_translate_build_lint`
    in `tests/test_vendor_mv_lib.py`. `_STRIP_PREFIXES` is anchored on
    `"import ts_cli."` / `"import ts_cli "` (not bare `"import ts_cli"`) so it
    does not also match `import ts_client` (Genie's `%run ts_client` counterpart,
    string-prefix-adjacent to `ts_cli`)."""
    out: list[str] = []
    lines = source.splitlines()
    i = 0
    while i < len(lines):
        stripped = lines[i].lstrip()
        if any(stripped.startswith(p) for p in _STRIP_PREFIXES):
            depth = lines[i].count("(") - lines[i].count(")")
            i += 1
            while depth > 0 and i < len(lines):
                depth += lines[i].count("(") - lines[i].count(")")
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def assert_no_duplicate_top_level_names(parts: dict[str, str]) -> None:
    """Concatenation puts every module in one namespace — a name defined twice
    would silently shadow. Fail the build instead."""
    owners: dict[str, str] = {}
    for path, src in parts.items():
        for node in ast.parse(src).body:
            names: list[str] = []
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                names = [node.name]
            elif isinstance(node, ast.Assign):
                names = [t.id for t in node.targets if isinstance(t, ast.Name)]
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                names = [node.target.id]
            for name in names:
                if name in owners and owners[name] != path:
                    raise SystemExit(
                        f"duplicate top-level name '{name}' in {path} and "
                        f"{owners[name]} — rename one before vendoring")
                owners[name] = path


def _ts_cli_version(ts_cli_root: pathlib.Path) -> str:
    init = (ts_cli_root / "ts_cli" / "__init__.py").read_text()
    m = re.search(r'__version__\s*=\s*"([^"]+)"', init)
    return m.group(1) if m else "unknown"


def build_source(ts_cli_root: pathlib.Path) -> str:
    ts_cli_root = pathlib.Path(ts_cli_root)
    parts: dict[str, str] = {}
    for rel in CLOSURE:
        raw = (ts_cli_root / rel).read_text()
        parts[rel] = strip_internal_imports(raw)
    assert_no_duplicate_top_level_names(parts)
    header = (
        "# Databricks notebook source\n"
        '"""databricks_mv_lib — vendored from ts-cli '
        f"v{_ts_cli_version(ts_cli_root)} (BL-063 PR 5).\n\n"
        "GENERATED by agents/databricks/build_mv_lib.py at deploy time — do not\n"
        "edit here; edit tools/ts-cli/ts_cli/ and redeploy. Pure functions only\n"
        "(stdlib + PyYAML): parse_metric_view, translate_metric_view,\n"
        "build_table_tml, build_model_tml_dbx, validate_tml_invariants,\n"
        "lint_tml, dump_tml_yaml, extract_imported_guid.\n"
        '"""\n'
        "from __future__ import annotations\n"
    )
    body = "\n\n".join(
        f"# {'-' * 75}\n# vendored: {rel}\n# {'-' * 75}\n{src}"
        for rel, src in parts.items())
    source = header + "\n" + body + "\n"
    compile(source, "databricks_mv_lib", "exec")  # syntax gate
    return source


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ts-cli-root", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    args = ap.parse_args()
    source = build_source(args.ts_cli_root)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(source)
    print(f"wrote {args.out} ({len(source.splitlines())} lines)", file=sys.stderr)


if __name__ == "__main__":
    main()
